# Generated by Django 3.2.20 on 2023-09-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_used', models.CharField(max_length=50)),
                ('Reading', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Last_date', models.DateField()),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Pin', models.BigIntegerField()),
                ('Consumer_no', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Report_emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Description', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Fine', models.CharField(max_length=50)),
                ('BILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.bill')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('AUTHORITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Date', models.DateField()),
                ('T_Date', models.DateField()),
                ('Reason', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=100)),
                ('AUTHORITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user'),
        ),
        migrations.AddField(
            model_name='authority',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.login'),
        ),
    ]
