# Generated by Django 3.2.20 on 2023-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_auto_20231007_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='Designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
