# Generated by Django 3.2.24 on 2024-02-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0004_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Confirm_password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
        migrations.AddField(
            model_name='register',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smartapp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='Last_date',
            field=models.DateField(),
        ),
    ]
